"""Compatibility shim for the extracted triage-report skill."""

from tizen_triage_report.gbs_report import (
    DEFAULT_ARCHES,
    GbsReport,
    GbsReportPackage,
    _Anchor,
    _AnchorBuilder,
    _attrs_to_map,
    _Cell,
    _CellBuilder,
    _class_names,
    _IframeParser,
    _looks_like_build_status_table,
    _normalize_text,
    _ReportTableParser,
    _Row,
    _row_to_package,
    _status_from_anchor,
    _Table,
    download_gbs_package_buildlog,
    fetch_gbs_report,
    find_iframe_src,
    parse_gbs_report_packages,
)

__all__ = [
    "DEFAULT_ARCHES",
    "GbsReport",
    "GbsReportPackage",
    "_Anchor",
    "_AnchorBuilder",
    "_Cell",
    "_CellBuilder",
    "_IframeParser",
    "_ReportTableParser",
    "_Row",
    "_Table",
    "_attrs_to_map",
    "_class_names",
    "_looks_like_build_status_table",
    "_normalize_text",
    "_row_to_package",
    "_status_from_anchor",
    "download_gbs_package_buildlog",
    "fetch_gbs_report",
    "find_iframe_src",
    "parse_gbs_report_packages",
]
