"""Compatibility re-exports for QuickBuild HTTP helpers moved in P4.9."""

from tizen_ci_shared.quickbuild_http import DEFAULT_COOKIE_PATH as DEFAULT_COOKIE_PATH
from tizen_ci_shared.quickbuild_http import (
    DEFAULT_QUICKBUILD_BASE_URL as DEFAULT_QUICKBUILD_BASE_URL,
)
from tizen_ci_shared.quickbuild_http import DOWNLOAD_LINK_MARKER as DOWNLOAD_LINK_MARKER
from tizen_ci_shared.quickbuild_http import DOWNLOAD_TIZEN_BASE_URL as DOWNLOAD_TIZEN_BASE_URL
from tizen_ci_shared.quickbuild_http import HttpFetcher as HttpFetcher
from tizen_ci_shared.quickbuild_http import HttpResponse as HttpResponse
from tizen_ci_shared.quickbuild_http import PackageBuildLog as PackageBuildLog
from tizen_ci_shared.quickbuild_http import QuickBuildDownload as QuickBuildDownload
from tizen_ci_shared.quickbuild_http import QuickBuildError as QuickBuildError
from tizen_ci_shared.quickbuild_http import _raise_if_login_page as _raise_if_login_page
from tizen_ci_shared.quickbuild_http import _urllib_fetch as _urllib_fetch
from tizen_ci_shared.quickbuild_http import (
    derive_package_buildlog_url as derive_package_buildlog_url,
)
from tizen_ci_shared.quickbuild_http import download_full_log as download_full_log
from tizen_ci_shared.quickbuild_http import download_package_buildlog as download_package_buildlog
from tizen_ci_shared.quickbuild_http import find_download_href as find_download_href
from tizen_ci_shared.quickbuild_http import load_cookie_jar as load_cookie_jar
from tizen_ci_shared.quickbuild_http import normalize_quickbuild_url as normalize_quickbuild_url
