<!-- BEGIN GENERATED predicates renderer_version=1 -->

### OBS-1.item1-basis

对象: step-0 v2.1-FROZEN §6.2 的 shim 删除清单作为台账第一段的来源;量词: ∀。
- [§2+§3:OBS-1.item1-basis] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(eq)","子节点(matches)","子节点(nonempty)","子节点(forall)","子节点(forall)","子节点(subset)"]
- [G1] 等于: ["/claim_id","OBS-1.item1-basis"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-1.item1-basis#1] 等于: ["/source/path","docs/clang-fix-campaign/p49-step0-design-v2.1-FROZEN.md"]
- [OBS-1.item1-basis#2] 正则匹配: ["/source/heading","^### 6\\.2 "]
- [OBS-1.item1-basis#3] 集合或字符串非空: ["/entries"]
- [OBS-1.item1-basis#4] 逐元素全部满足: ["/entries/*","子节点(in)"]
- [OBS-1.item1-basis#4] 属于常量集合: ["@/kind",["REEXPORT_SURFACE","SYMBOL_GROUP","PACKAGE_REEXPORT","NEGATIVE"]]
- [OBS-1.item1-basis#5] 逐元素全部满足: ["/entries/*","子节点(implies)"]
- [OBS-1.item1-basis#5] 前件成立则后件成立: ["子节点(ne)","子节点(nonempty)"]
- [OBS-1.item1-basis#5] 不等于: ["@/kind","NEGATIVE"]
- [OBS-1.item1-basis#5] 集合或字符串非空: ["@/mapped_ledger_keys"]
- [OBS-1.item1-basis#6] 集合包含: ["/entries/*/mapped_ledger_keys/*","子节点($file)"]
- [OBS-1.item1-basis#6] 读取独立产物的事实: ["E/ledger_inventory.json","/seg1/*/ledger_key"]

### OBS-1.item2-scope

对象: skill-4 v1.12.1-FROZEN 登记的测试私有件义务与 `private_consumption.json` 的对应;量词: ∀。
- [§2+§3:OBS-1.item2-scope] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(eq)","子节点(nonempty)","子节点(set_eq)","子节点(forall)","子节点(forall)","子节点(forall)","子节点(eq)","子节点(set_eq)"]
- [G1] 等于: ["/claim_id","OBS-1.item2-scope"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-1.item2-scope#1] 等于: ["/obligation_source/path","docs/clang-fix-campaign/p49-skill4-build-verify-design-v1.12.1-FROZEN.md"]
- [OBS-1.item2-scope#2] 集合或字符串非空: ["/obligations"]
- [OBS-1.item2-scope#3] 集合相等: ["/mapping/*/obligation_id","/obligations/*/obligation_id"]
- [OBS-1.item2-scope#4] 逐元素全部满足: ["/mapping/*","子节点(in)"]
- [OBS-1.item2-scope#4] 属于常量集合: ["@/status",["HAS_CONSUMERS","NO_CURRENT_CONSUMER"]]
- [OBS-1.item2-scope#5] 逐元素全部满足: ["/mapping/*","子节点(implies)"]
- [OBS-1.item2-scope#5] 前件成立则后件成立: ["子节点(eq)","子节点(nonempty)"]
- [OBS-1.item2-scope#5] 等于: ["@/status","HAS_CONSUMERS"]
- [OBS-1.item2-scope#5] 集合或字符串非空: ["@/consumption_ids"]
- [OBS-1.item2-scope#6] 逐元素全部满足: ["/mapping/*","子节点(implies)"]
- [OBS-1.item2-scope#6] 前件成立则后件成立: ["子节点(eq)","子节点(count)"]
- [OBS-1.item2-scope#6] 等于: ["@/status","NO_CURRENT_CONSUMER"]
- [OBS-1.item2-scope#6] 元素计数比较: ["@/consumption_ids",0];比较符 ==
- [OBS-1.item2-scope#7] 等于: ["/consumption_ref/path","docs/clang-fix-campaign/dev_memory/stage14_p49_terminal_batch/a0-evidence/private_consumption.json"]
- [OBS-1.item2-scope#8] 集合相等: ["子节点($file)","子节点(union)"]
- [OBS-1.item2-scope#8] 读取独立产物的事实: ["E/private_consumption.json","/entries/*/id"]
- [OBS-1.item2-scope#8] 集合并: ["/mapping/*/consumption_ids/*","/unmapped_consumption_ids/*"]

### OBS-1.item3-predicate

对象: `ANCHOR-3` 的现状判定式与四个相邻输入下的现状行为;量词: ∀。
- [§2+§3:OBS-1.item3-predicate] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(eq)","子节点(eq)","子节点(all)","子节点(set_eq)","子节点(all)","子节点(forall)"]
- [G1] 等于: ["/claim_id","OBS-1.item3-predicate"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-1.item3-predicate#1] 等于: ["/anchor/file","tizen-gerrit-fetch/scripts/tizen_gerrit_fetch/gerrit.py"]
- [OBS-1.item3-predicate#2] 等于: ["/anchor/matched_count",1]
- [OBS-1.item3-predicate#3] 所有条件成立: ["子节点(eq)","子节点(subset)","子节点(eq)"]
- [OBS-1.item3-predicate#3] 等于: ["/anchor/expr_kind","BoolOp.And"]
- [OBS-1.item3-predicate#3] 集合包含: [["exists","is_symlink"],"/anchor/operand_calls"]
- [OBS-1.item3-predicate#3] 等于: ["/anchor/same_receiver",true]
- [OBS-1.item3-predicate#4] 集合相等: ["/scenarios/*/scenario_id",["DANGLING_SYMLINK","LIVE_SYMLINK_TO_DIR","REAL_DIR","ABSENT"]]
- [OBS-1.item3-predicate#5] 所有条件成立: ["子节点(forall)","子节点(forall)"]
- [OBS-1.item3-predicate#5] 逐元素全部满足: ["/scenarios/*","子节点(implies)"]
- [OBS-1.item3-predicate#5] 前件成立则后件成立: ["子节点(eq)","子节点(all)"]
- [OBS-1.item3-predicate#5] 等于: ["@/scenario_id","LIVE_SYMLINK_TO_DIR"]
- [OBS-1.item3-predicate#5] 所有条件成立: ["子节点(eq)","子节点(eq)","子节点(eq)"]
- [OBS-1.item3-predicate#5] 等于: ["@/exception_type","GerritError"]
- [OBS-1.item3-predicate#5] 等于: ["@/exception_code/state","VALUE"]
- [OBS-1.item3-predicate#5] 等于: ["@/exception_code/value","SOURCE_DIR_UNSAFE"]
- [OBS-1.item3-predicate#5] 逐元素全部满足: ["/scenarios/*","子节点(implies)"]
- [OBS-1.item3-predicate#5] 前件成立则后件成立: ["子节点(eq)","子节点(all)"]
- [OBS-1.item3-predicate#5] 等于: ["@/scenario_id","DANGLING_SYMLINK"]
- [OBS-1.item3-predicate#5] 所有条件成立: ["子节点(present)","子节点(in)","子节点(any)"]
- [OBS-1.item3-predicate#5] 路径存在且非空值: ["@/exception_type"]
- [OBS-1.item3-predicate#5] 属于常量集合: ["@/exception_code/state",["ABSENT","VALUE"]]
- [OBS-1.item3-predicate#5] 至少一项成立: ["子节点(eq)","子节点(all)"]
- [OBS-1.item3-predicate#5] 等于: ["@/exception_code/state","ABSENT"]
- [OBS-1.item3-predicate#5] 所有条件成立: ["子节点(eq)","子节点(ne)"]
- [OBS-1.item3-predicate#5] 等于: ["@/exception_code/state","VALUE"]
- [OBS-1.item3-predicate#5] 不等于: ["@/exception_code/value","SOURCE_DIR_UNSAFE"]
- [OBS-1.item3-predicate#6] 逐元素全部满足: ["/scenarios/*","子节点(present)"]
- [OBS-1.item3-predicate#6] 路径存在且非空值: ["@/destination_after"]

### OBS-1.item4-anchors

对象: skill-5 v1.3.2-FROZEN §3.2 映射表的行与顺序、六个调用面的定位、以及三处残留格的现状观测;量词: ∀。
- [§2+§3:OBS-1.item4-anchors] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(all)","子节点(count)","子节点(all)","子节点(all)","子节点(forall)","子节点(all)","子节点(all)","子节点(all)"]
- [G1] 等于: ["/claim_id","OBS-1.item4-anchors"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-1.item4-anchors#1] 所有条件成立: ["子节点(eq)","子节点(matches)"]
- [OBS-1.item4-anchors#1] 等于: ["/table_source/path","docs/clang-fix-campaign/p49-skill5-gerrit-submit-design-v1.3.2-FROZEN.md"]
- [OBS-1.item4-anchors#1] 正则匹配: ["/table_source/heading","^### 3\\.2 "]
- [OBS-1.item4-anchors#2] 元素计数比较: ["/rows",6];比较符 ==
- [OBS-1.item4-anchors#3] 所有条件成立: ["子节点(matches)","子节点(matches)","子节点(matches)","子节点(matches)","子节点(matches)","子节点(matches)"]
- [OBS-1.item4-anchors#3] 正则匹配: ["/rows/0/surface","query 阶段"]
- [OBS-1.item4-anchors#3] 正则匹配: ["/rows/1/surface","git 阶段"]
- [OBS-1.item4-anchors#3] 正则匹配: ["/rows/2/surface","本 skill .*_run_git"]
- [OBS-1.item4-anchors#3] 正则匹配: ["/rows/3/surface","ls-remote"]
- [OBS-1.item4-anchors#3] 正则匹配: ["/rows/4/surface","shared/workspace .*_run_git"]
- [OBS-1.item4-anchors#3] 正则匹配: ["/rows/5/surface","_exclude_private_files"]
- [OBS-1.item4-anchors#4] 所有条件成立: ["子节点(matches)","子节点(matches)","子节点(matches)","子节点(matches)","子节点(matches)","子节点(matches)"]
- [OBS-1.item4-anchors#4] 正则匹配: ["/rows/0/timeout_cell","FETCH_TIMEOUT"]
- [OBS-1.item4-anchors#4] 正则匹配: ["/rows/1/timeout_cell","FETCH_TIMEOUT"]
- [OBS-1.item4-anchors#4] 正则匹配: ["/rows/2/timeout_cell","GerritSubmitError.*GIT_TIMEOUT"]
- [OBS-1.item4-anchors#4] 正则匹配: ["/rows/3/timeout_cell","target_head_unknown:timeout"]
- [OBS-1.item4-anchors#4] 正则匹配: ["/rows/4/timeout_cell","GIT_TIMEOUT:"]
- [OBS-1.item4-anchors#4] 正则匹配: ["/rows/5/timeout_cell","GIT_TIMEOUT"]
- [OBS-1.item4-anchors#5] 逐元素全部满足: ["/rows/*","子节点(matches)"]
- [OBS-1.item4-anchors#5] 正则匹配: ["@/interrupt_cell","^传播$"]
- [OBS-1.item4-anchors#6] 所有条件成立: ["子节点(matches)","子节点(matches)","子节点(matches)"]
- [OBS-1.item4-anchors#6] 正则匹配: ["/rows/0/residual_cell","destination 不动"]
- [OBS-1.item4-anchors#6] 正则匹配: ["/rows/1/residual_cell","阶段残留"]
- [OBS-1.item4-anchors#6] 正则匹配: ["/rows/5/residual_cell","protected marker 尚未写入"]
- [OBS-1.item4-anchors#7] 所有条件成立: ["子节点(count)","子节点(seq_eq)","子节点(forall)"]
- [OBS-1.item4-anchors#7] 元素计数比较: ["/call_sites",6];比较符 ==
- [OBS-1.item4-anchors#7] 序列相等: ["/call_sites/*/anchor_no",[1,2,3,4,5,6]]
- [OBS-1.item4-anchors#7] 逐元素全部满足: ["/call_sites/*","子节点(eq)"]
- [OBS-1.item4-anchors#7] 等于: ["@/matched_count",1]
- [OBS-1.item4-anchors#8] 所有条件成立: ["子节点(forall)","子节点(exists)","子节点(forall)","子节点(set_eq)"]
- [OBS-1.item4-anchors#8] 逐元素全部满足: ["/residual_obs/*","子节点(implies)"]
- [OBS-1.item4-anchors#8] 前件成立则后件成立: ["子节点(eq)","子节点(eq)"]
- [OBS-1.item4-anchors#8] 等于: ["@/anchor_no",1]
- [OBS-1.item4-anchors#8] 等于: ["@/destination_unchanged",true]
- [OBS-1.item4-anchors#8] 存在满足的元素: ["/residual_obs/*","子节点(eq)"]
- [OBS-1.item4-anchors#8] 等于: ["@/anchor_no",2]
- [OBS-1.item4-anchors#8] 逐元素全部满足: ["/residual_obs/*","子节点(implies)"]
- [OBS-1.item4-anchors#8] 前件成立则后件成立: ["子节点(eq)","子节点(all)"]
- [OBS-1.item4-anchors#8] 等于: ["@/anchor_no",6]
- [OBS-1.item4-anchors#8] 所有条件成立: ["子节点(eq)","子节点(eq)","子节点(eq)"]
- [OBS-1.item4-anchors#8] 等于: ["@/workdir_marker/state","PRESENT"]
- [OBS-1.item4-anchors#8] 等于: ["@/protected_marker/state","ABSENT"]
- [OBS-1.item4-anchors#8] 等于: ["@/exclude_completed",false]
- [OBS-1.item4-anchors#8] 集合相等: ["/residual_obs/*/anchor_no",[1,2,6]]

### OBS-1.item5-order

对象: `mark_worktree_protected` 的调用顺序、两个中断时点的失败态、既有读取方对其的结果;量词: ∀。
- [§2+§3:OBS-1.item5-order] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(seq_eq)","子节点(set_eq)","子节点(forall)","子节点(forall)","子节点(forall)","子节点(forall)","子节点(forall)","子节点(forall)"]
- [G1] 等于: ["/claim_id","OBS-1.item5-order"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-1.item5-order#1] 序列相等: ["/call_order",["_verify_cleanup_handle","_exclude_private_files","write_protected_marker"]]
- [OBS-1.item5-order#2] 集合相等: ["/scenarios/*/scenario_id",["EXCLUDE_INTERRUPTED","MARKER_WRITE_INTERRUPTED"]]
- [OBS-1.item5-order#3] 逐元素全部满足: ["/scenarios/*","子节点(implies)"]
- [OBS-1.item5-order#3] 前件成立则后件成立: ["子节点(eq)","子节点(eq)"]
- [OBS-1.item5-order#3] 等于: ["@/scenario_id","EXCLUDE_INTERRUPTED"]
- [OBS-1.item5-order#3] 等于: ["@/protected_marker/state","ABSENT"]
- [OBS-1.item5-order#4] 逐元素全部满足: ["/scenarios/*","子节点(implies)"]
- [OBS-1.item5-order#4] 前件成立则后件成立: ["子节点(eq)","子节点(in)"]
- [OBS-1.item5-order#4] 等于: ["@/scenario_id","MARKER_WRITE_INTERRUPTED"]
- [OBS-1.item5-order#4] 属于常量集合: ["@/protected_marker/state",["ABSENT","PARTIAL"]]
- [OBS-1.item5-order#5] 逐元素全部满足: ["/scenarios/*","子节点(implies)"]
- [OBS-1.item5-order#5] 前件成立则后件成立: ["子节点(eq)","子节点(present)"]
- [OBS-1.item5-order#5] 等于: ["@/protected_marker/state","PARTIAL"]
- [OBS-1.item5-order#5] 路径存在且非空值: ["@/protected_marker/sha256"]
- [OBS-1.item5-order#6] 逐元素全部满足: ["/scenarios/*","子节点(all)"]
- [OBS-1.item5-order#6] 所有条件成立: ["子节点(nonempty)","子节点(exists)"]
- [OBS-1.item5-order#6] 集合或字符串非空: ["@/readers"]
- [OBS-1.item5-order#6] 存在满足的元素: ["@/readers/*","子节点(eq)"]
- [OBS-1.item5-order#6] 等于: ["@/reader","is_protected"]
- [OBS-1.item5-order#7] 逐元素全部满足: ["/scenarios/*","子节点(set_eq)"]
- [OBS-1.item5-order#7] 集合相等: ["@/readers/*/reader","子节点($file)"]
- [OBS-1.item5-order#7] 读取独立产物的事实: ["E/B-1-anchors.json","/protected_marker_readers/*"]
- [OBS-1.item5-order#8] 逐元素全部满足: ["/scenarios/*/readers/*","子节点(in)"]
- [OBS-1.item5-order#8] 属于常量集合: ["@/result_kind",["RETURN","EXCEPTION"]]

### OBS-2.seg1-staleness

对象: step-0 §6.2 每个条目在当前树上是否仍然成立;量词: ∀。
- [§2+§3:OBS-2.seg1-staleness] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(set_eq)","子节点(forall)","子节点(forall)"]
- [G1] 等于: ["/claim_id","OBS-2.seg1-staleness"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-2.seg1-staleness#1] 集合相等: ["/entries/*/entry_id","子节点($ref)"]
- [OBS-2.seg1-staleness#1] 读取另一 claim 的事实: ["OBS-1.item1-basis","/entries/*/entry_id"]
- [OBS-2.seg1-staleness#2] 逐元素全部满足: ["/entries/*","子节点(in)"]
- [OBS-2.seg1-staleness#2] 属于常量集合: ["@/staleness",["CURRENT","STALE"]]
- [OBS-2.seg1-staleness#3] 逐元素全部满足: ["/entries/*","子节点(all)"]
- [OBS-2.seg1-staleness#3] 所有条件成立: ["子节点(present)","子节点(present)"]
- [OBS-2.seg1-staleness#3] 路径存在且非空值: ["@/current_fact/exists"]
- [OBS-2.seg1-staleness#3] 路径存在且非空值: ["@/current_fact/shape"]

### OBS-2.seg2-form

对象: step-0 与 skill-1…6 共七份 closeout 中 shim 相关条目的形态与可用性;量词: ∀。
- [§2+§3:OBS-2.seg2-form] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(set_eq)","子节点(forall)","子节点(forall)","子节点(forall)","子节点(forall)"]
- [G1] 等于: ["/claim_id","OBS-2.seg2-form"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-2.seg2-form#1] 集合相等: ["/sources/*/batch",["step-0","skill-1","skill-2","skill-3","skill-4","skill-5","skill-6"]]
- [OBS-2.seg2-form#2] 逐元素全部满足: ["/sources/*","子节点(matches)"]
- [OBS-2.seg2-form#2] 正则匹配: ["@/path","^docs/clang-fix-campaign/review/p49-(step0|skill[1-6])-closeout\\.md$"]
- [OBS-2.seg2-form#3] 逐元素全部满足: ["/sources/*","子节点(in)"]
- [OBS-2.seg2-form#3] 属于常量集合: ["@/form",["STRUCTURED_TABLE","PROSE","NONE"]]
- [OBS-2.seg2-form#4] 逐元素全部满足: ["/sources/*","子节点(implies)"]
- [OBS-2.seg2-form#4] 前件成立则后件成立: ["子节点(eq)","子节点(eq)"]
- [OBS-2.seg2-form#4] 等于: ["@/usable_as_coverage",true]
- [OBS-2.seg2-form#4] 等于: ["@/form","STRUCTURED_TABLE"]
- [OBS-2.seg2-form#5] 逐元素全部满足: ["/sources/*","子节点(implies)"]
- [OBS-2.seg2-form#5] 前件成立则后件成立: ["子节点(eq)","子节点(eq)"]
- [OBS-2.seg2-form#5] 等于: ["@/form","NONE"]
- [OBS-2.seg2-form#5] 等于: ["@/entry_count",0]

### OBS-3.commit-order

对象: skill-3 批次登记的抽取提交、测试提交,以及使旧址模块变为 shim 的提交;量词: ∀。
- [§2+§3:OBS-3.commit-order] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(all)","子节点(all)","子节点(forall)"]
- [G1] 等于: ["/claim_id","OBS-3.commit-order"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-3.commit-order#1] 所有条件成立: ["子节点(eq)","子节点(eq)","子节点(matches)"]
- [OBS-3.commit-order#1] 等于: ["/batch","skill-3"]
- [OBS-3.commit-order#1] 等于: ["/registered_extraction_sha/source_path","docs/clang-fix-campaign/review/p49-skill3-closeout.md"]
- [OBS-3.commit-order#1] 正则匹配: ["/registered_extraction_sha/value","^[0-9a-f]{40}$"]
- [OBS-3.commit-order#2] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [OBS-3.commit-order#2] 集合或字符串非空: ["/shim_creations"]
- [OBS-3.commit-order#2] 逐元素全部满足: ["/shim_creations/*","子节点(all)"]
- [OBS-3.commit-order#2] 所有条件成立: ["子节点(matches)","子节点(not)","子节点(eq)"]
- [OBS-3.commit-order#2] 正则匹配: ["@/creating_sha","^[0-9a-f]{40}$"]
- [OBS-3.commit-order#2] 条件取反: ["子节点(eq)"]
- [OBS-3.commit-order#2] 等于: ["@/pre_def_count",0]
- [OBS-3.commit-order#2] 等于: ["@/post_def_count",0]
- [OBS-3.commit-order#3] 逐元素全部满足: ["/relations/*","子节点(in)"]
- [OBS-3.commit-order#3] 属于常量集合: ["@/relation",["ANCESTOR","DESCENDANT","SAME","UNRELATED"]]

### OBS-3.transition-map

对象: 当前树中每个旧址整模块 shim 由哪一批、哪一个提交创建;量词: ∀。
- [§2+§3:OBS-3.transition-map] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(forall)","子节点(forall)","子节点(forall)","子节点(forall)","子节点(set_eq)"]
- [G1] 等于: ["/claim_id","OBS-3.transition-map"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-3.transition-map#1] 逐元素全部满足: ["/modules/*","子节点(in)"]
- [OBS-3.transition-map#1] 属于常量集合: ["@/creating_batch",["step-0","skill-1","skill-2","skill-3","skill-4","skill-5","skill-6","UNREGISTERED"]]
- [OBS-3.transition-map#2] 逐元素全部满足: ["/modules/*","子节点(implies)"]
- [OBS-3.transition-map#2] 前件成立则后件成立: ["子节点(ne)","子节点(all)"]
- [OBS-3.transition-map#2] 不等于: ["@/creating_batch","UNREGISTERED"]
- [OBS-3.transition-map#2] 所有条件成立: ["子节点(not)","子节点(eq)"]
- [OBS-3.transition-map#2] 条件取反: ["子节点(eq)"]
- [OBS-3.transition-map#2] 等于: ["@/pre_def_count",0]
- [OBS-3.transition-map#2] 等于: ["@/post_def_count",0]
- [OBS-3.transition-map#3] 逐元素全部满足: ["/modules/*","子节点(implies)"]
- [OBS-3.transition-map#3] 前件成立则后件成立: ["子节点(ne)","子节点(in_path)"]
- [OBS-3.transition-map#3] 不等于: ["@/creating_batch","UNREGISTERED"]
- [OBS-3.transition-map#3] 属于路径集合: ["@/creating_sha","子节点($file)"]
- [OBS-3.transition-map#3] 读取独立产物的事实: ["E/B-2-sources.json","/registered_extraction_shas/*"]
- [OBS-3.transition-map#4] 逐元素全部满足: ["/modules/*","子节点(in)"]
- [OBS-3.transition-map#4] 属于常量集合: ["@/uncovered_class",["NONE","a","b","b'","c","d","e","f","g","h"]]
- [OBS-3.transition-map#5] 集合相等: ["/modules/*/path","子节点($file)"]
- [OBS-3.transition-map#5] 读取独立产物的事实: ["E/raw_findings.json","/module_granularity_old_location_paths/*"]

### OBS-4.owner-attribution

对象: 每个 A=是 的 binding 候选(`#REEXPORT`/`#INLINE`)所导入符号的定义位置;量词: ∀。
- [§2+§3:OBS-4.owner-attribution] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(set_eq)","子节点(forall)","子节点(forall)","子节点(forall)"]
- [G1] 等于: ["/claim_id","OBS-4.owner-attribution"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-4.owner-attribution#1] 集合相等: ["/records/*/candidate_id","子节点($file)"]
- [OBS-4.owner-attribution#1] 读取独立产物的事实: ["E/B-15-disposition_evidence.json","/a_true_binding_candidates/*"]
- [OBS-4.owner-attribution#2] 逐元素全部满足: ["/records/*","子节点(count)"]
- [OBS-4.owner-attribution#2] 元素计数比较: ["@/definition_sites",1];比较符 >=
- [OBS-4.owner-attribution#3] 逐元素全部满足: ["/records/*","子节点(implies)"]
- [OBS-4.owner-attribution#3] 前件成立则后件成立: ["子节点(count)","子节点(present)"]
- [OBS-4.owner-attribution#3] 元素计数比较: ["@/definition_sites",1];比较符 ==
- [OBS-4.owner-attribution#3] 路径存在且非空值: ["@/owner_outside_host"]
- [OBS-4.owner-attribution#4] 逐元素全部满足: ["/records/*","子节点(implies)"]
- [OBS-4.owner-attribution#4] 前件成立则后件成立: ["子节点(not)","子节点(eq)"]
- [OBS-4.owner-attribution#4] 条件取反: ["子节点(count)"]
- [OBS-4.owner-attribution#4] 元素计数比较: ["@/definition_sites",1];比较符 ==
- [OBS-4.owner-attribution#4] 等于: ["@/owner_module","AMBIGUOUS"]

### OBS-5.entry-consumers

对象: 仓库全部已文档化入口(打包入口、包的 `__main__`、各 SKILL.md 中写明的命令)及其 smoke 结果;量词: ∀。
- [§2+§3:OBS-5.entry-consumers] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(forall)","子节点(set_eq)","子节点(forall)","子节点(forall)"]
- [G1] 等于: ["/claim_id","OBS-5.entry-consumers"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-5.entry-consumers#1] 逐元素全部满足: ["/entries/*","子节点(in)"]
- [OBS-5.entry-consumers#1] 属于常量集合: ["@/kind",["CONSOLE_SCRIPT","PACKAGE_MAIN","SKILL_MD_COMMAND"]]
- [OBS-5.entry-consumers#2] 集合相等: ["/entries/*/entry_id","子节点($file)"]
- [OBS-5.entry-consumers#2] 读取独立产物的事实: ["E/B-5-entries.json","/independent_enumeration/*"]
- [OBS-5.entry-consumers#3] 逐元素全部满足: ["/entries/*","子节点(all)"]
- [OBS-5.entry-consumers#3] 所有条件成立: ["子节点(nonempty)","子节点(present)","子节点(eq)"]
- [OBS-5.entry-consumers#3] 集合或字符串非空: ["@/documented_in"]
- [OBS-5.entry-consumers#3] 路径存在且非空值: ["@/smoke_command"]
- [OBS-5.entry-consumers#3] 等于: ["@/smoke_exit",0]
- [OBS-5.entry-consumers#4] 逐元素全部满足: ["/entries/*","子节点(not)"]
- [OBS-5.entry-consumers#4] 条件取反: ["子节点(matches)"]
- [OBS-5.entry-consumers#4] 正则匹配: ["@/smoke_command","(^|\\s)tests/"]

### OBS-6.proxy-count

对象: 当前树上的 `PROXY_CALLABLE` 候选;量词: 计数。
- [§2+§3:OBS-6.proxy-count] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(count)","子节点(set_eq)","子节点(all)"]
- [G1] 等于: ["/claim_id","OBS-6.proxy-count"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-6.proxy-count#1] 元素计数比较: ["/candidate_ids","子节点($value)"];比较符 ==
- [OBS-6.proxy-count#1] 读取标量: ["/count"]
- [OBS-6.proxy-count#2] 集合相等: ["/candidate_ids","子节点($file)"]
- [OBS-6.proxy-count#2] 读取独立产物的事实: ["E/raw_findings.json","/proxy_candidate_ids/*"]
- [OBS-6.proxy-count#3] 所有条件成立: ["子节点(subset)","子节点(sum_eq)"]
- [OBS-6.proxy-count#3] 集合包含: ["子节点(keys)",["DIRECT","PARTIAL_FORWARD","METHOD_LEVEL","DECORATOR_GENERATED","HOST_SIDE_EFFECT"]]
- [OBS-6.proxy-count#3] 对象键数组: ["/by_form"]
- [OBS-6.proxy-count#3] 数值和相等: ["/by_form","/count"]

### OBS-6.intra-package-shim

对象: 宿主与委托目标位于同一顶层包的兼容壳;量词: ∃/¬∃ 如实记录。
- [§2+§3:OBS-6.intra-package-shim] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(forall)","子节点(subset)","子节点(set_eq)"]
- [G1] 等于: ["/claim_id","OBS-6.intra-package-shim"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-6.intra-package-shim#1] 逐元素全部满足: ["/records/*","子节点(eq_path)"]
- [OBS-6.intra-package-shim#1] 两路径值相等: ["@/host_top_package","@/target_top_package"]
- [OBS-6.intra-package-shim#2] 集合包含: ["/records/*/candidate_id","子节点($file)"]
- [OBS-6.intra-package-shim#2] 读取独立产物的事实: ["E/raw_findings.json","/all_candidate_ids/*"]
- [OBS-6.intra-package-shim#3] 集合相等: ["/records/*/candidate_id","子节点($file)"]
- [OBS-6.intra-package-shim#3] 读取独立产物的事实: ["E/raw_findings.json","/same_top_package_candidate_ids/*"]

### OBS-7.falsification-samples

对象: 三份前批 ledger 中登记的现存漏检样本,以及消费者引擎对它们的命中;量词: ∀。
- [§2+§3:OBS-7.falsification-samples] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(nonempty)","子节点(set_eq)","子节点(forall)","子节点(nonempty)"]
- [G1] 等于: ["/claim_id","OBS-7.falsification-samples"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-7.falsification-samples#1] 集合或字符串非空: ["/samples"]
- [OBS-7.falsification-samples#2] 集合相等: ["/hits/*/sample_id","/samples/*/sample_id"]
- [OBS-7.falsification-samples#3] 逐元素全部满足: ["/samples/*","子节点(in)"]
- [OBS-7.falsification-samples#3] 属于常量集合: ["@/form",["C1","C4","C5a","C2a","C2b","C3","C6a","C6b","C5b","C5c","C5d","C5e","C6c","C6d","C8a","C8b","C7a","C7b","C7c","C7d"]]
- [OBS-7.falsification-samples#4] 集合或字符串非空: ["/sources"]

### OBS-7.class-c-projection

对象: 按 §2 三分规则落入 (c) 类(不可判定)的测试;量词: 计数。
- [§2+§3:OBS-7.class-c-projection] 所有条件成立: ["子节点(eq)","子节点(eq_path)","子节点(all)","子节点(schema_closed)","子节点(count)","子节点(set_eq)","子节点(set_eq)","子节点(forall)"]
- [G1] 等于: ["/claim_id","OBS-7.class-c-projection"]
- [G2] 两路径值相等: ["/snapshot","$ctx.tree"]
- [G3] 所有条件成立: ["子节点(nonempty)","子节点(forall)"]
- [G3] 集合或字符串非空: ["/evidence"]
- [G3] 逐元素全部满足: ["/evidence/*","子节点(any)"]
- [G3] 至少一项成立: ["子节点(all)","子节点(all)"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/command"]
- [G3] 路径存在且非空值: ["@/exit_code"]
- [G3] 路径存在且非空值: ["@/output_sha256"]
- [G3] 所有条件成立: ["子节点(present)","子节点(present)","子节点(present)"]
- [G3] 路径存在且非空值: ["@/path"]
- [G3] 路径存在且非空值: ["@/sha256"]
- [G3] 路径存在且非空值: ["@/selector"]
- [G4] 按完整 schema 逐层封闭核对: []
- [OBS-7.class-c-projection#1] 元素计数比较: ["/test_ids","子节点($value)"];比较符 ==
- [OBS-7.class-c-projection#1] 读取标量: ["/count"]
- [OBS-7.class-c-projection#2] 集合相等: ["/test_ids","子节点($file)"]
- [OBS-7.class-c-projection#2] 读取独立产物的事实: ["E/private_consumption.json","/class_c_test_ids/*"]
- [OBS-7.class-c-projection#3] 集合相等: ["子节点(keys)","/test_ids"]
- [OBS-7.class-c-projection#3] 对象键数组: ["/reasons"]
- [OBS-7.class-c-projection#4] 逐元素全部满足: ["子节点(values)","子节点(in)"]
- [OBS-7.class-c-projection#4] 对象值数组: ["/reasons"]
- [OBS-7.class-c-projection#4] 属于常量集合: ["@",["GRAPH_NOT_CLOSED","SEMANTICS_AMBIGUOUS","DYNAMIC_CALL_UNRESOLVED"]]
<!-- END GENERATED predicates -->
